### ISSUE TITLE
Configuration example / instructions

### ISSUE THREAD

**Issue by gioxx** [Ancocodet/wp-umami#15]
Ciao @Ancocodet and thanks for your plugin 😄 
I'm starting to use Umami, so I wanted to try Integrate Umami, but other than the website ID (which I found and added into plugin dashboard) I don't understand what data to report in the Script Url and Host Url fields. Do you mean https://analytics.umami.is/script.js for the first and the website URL in the second field?

Perhaps providing installation instructions in the readme file of the plugin (with examples) might make sense.
Meanwhile, I will make my contribution to correct a typo in the text and offer you the Italian localization if you like 👍 

Have a nice day.
Giovanni.

**Comment by Ancocodet** [comment]
There is actually an issue with the second one currently, but it should work when you set the script URL.
I will continue to improve the settings page, for easier configuration and add some information on the readme as well.

**Comment by Ancocodet** [comment]
I released a new version which fixed the issue with the option, documentation will be added soon.
