### ISSUE TITLE
Typo "instanace" --> "instance"

### ISSUE THREAD

**Issue by gioxx** [Ancocodet/wp-umami#16]
https://github.com/Ancocodet/wp-umami/blob/b22ec2e0cce94c7f3c6e3b452080bbbed3cc7b49/inc/templates/settings-page.php#L46

I was looking for the language files but I see that they don't currently seem to be provided, so I refer you directly to the affected line in the admin panel file 😃

**Comment by Ancocodet** [comment]
Fixed the typo while fixing the other issue.
